"""
Django settings for comfucius project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import redis

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# V's note: Read from environment variables
SECRET_KEY = os.getenv('COMFUCIUS_SECRETKEY', 'no-secret-key-set-in-environment-SET-ONE!')

# SECURITY WARNING: don't run with debug turned on in production!
# V's note: Read from environment variables
DEBUG = False

if os.environ.get('COMFUCIUS_DEBUG') is not None and os.environ.get('COMFUCIUS_DEBUG') == "True":
    print("[PYTHON] Debug mode enabled")
    DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'comfucius.xyz', 'www.comfucius.xyz']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Extra
    'pwa',
    'import_export',
    'redisboard',

    # My apps
    'quotes'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comfucius.urls'

CURRENT_THEME = "dimension-comfucius"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "themes", CURRENT_THEME)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'comfucius.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database/db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# https://stackoverflow.com/questions/8687927/difference-between-static-static-url-and-static-root-on-django

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATIC_URL = '/static/'


# 'python manage.py collectstatic' will collect files from STATICFILES_DIRS folder
# and will move them to STATIC_ROOT folder
# so they can be server easily from nginx

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "themes", CURRENT_THEME, 'static'),
)


# import_export settings

IMPORT_EXPORT_USE_TRANSACTIONS = True

# Redis

# Docker must use the redis service hostname. If not specified in env var, just use localhost
REDIS_HOST = os.getenv('COMFUCIUS_REDISHOST', 'localhost') 

REDIS_PORT = 6379
REDIS_INSTANCE = redis.StrictRedis(host=REDIS_HOST, port=REDIS_PORT, db=0)

# django-pwa

PWA_APP_DEBUG_MODE = True

PWA_APP_NAME = 'Comfucius'
PWA_APP_DESCRIPTION = "Per i tuoi bisogni di storpiata saggezza preconfezionata ed autoreferenziale"
PWA_APP_THEME_COLOR = '#FFFFFF'
PWA_APP_BACKGROUND_COLOR = '#FFFFFF'
PWA_APP_DISPLAY = 'minimal-ui'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/pwa/logo_192x.png',
        'sizes': '192x192',
        "type": "image/png",
        "purpose": "any maskable",
    },
    {
        'src': '/static/pwa/logo_512x.png',
        'sizes': '512x512',
        "type": "image/png",
        "purpose": "any maskable",
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'it-IT'
